//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BubbleDrawing.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameRevStruct", Namespace="http://schemas.datacontract.org/2004/07/EngrDrwTIFService")]
    [System.SerializableAttribute()]
    public partial struct NameRevStruct : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RevisionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Revision {
            get {
                return this.RevisionField;
            }
            set {
                if ((object.ReferenceEquals(this.RevisionField, value) != true)) {
                    this.RevisionField = value;
                    this.RaisePropertyChanged("Revision");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EngrDrwPkt", Namespace="http://schemas.datacontract.org/2004/07/EngrDrwTIFService")]
    [System.SerializableAttribute()]
    public partial class EngrDrwPkt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BubbleDrawing.ServiceReference1.FileObj[] FileObjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BubbleDrawing.ServiceReference1.NameRevStruct NameRevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WasCheckedOutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BubbleDrawing.ServiceReference1.FileObj[] FileObjects {
            get {
                return this.FileObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.FileObjectsField, value) != true)) {
                    this.FileObjectsField = value;
                    this.RaisePropertyChanged("FileObjects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BubbleDrawing.ServiceReference1.NameRevStruct NameRev {
            get {
                return this.NameRevField;
            }
            set {
                if ((this.NameRevField.Equals(value) != true)) {
                    this.NameRevField = value;
                    this.RaisePropertyChanged("NameRev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasCheckedOut {
            get {
                return this.WasCheckedOutField;
            }
            set {
                if ((this.WasCheckedOutField.Equals(value) != true)) {
                    this.WasCheckedOutField = value;
                    this.RaisePropertyChanged("WasCheckedOut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileObj", Namespace="http://schemas.datacontract.org/2004/07/EngrDrwTIFService")]
    [System.SerializableAttribute()]
    public partial class FileObj : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileBytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BubbleDrawing.ServiceReference1.MxFileFormats FileFmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileBytes {
            get {
                return this.FileBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.FileBytesField, value) != true)) {
                    this.FileBytesField = value;
                    this.RaisePropertyChanged("FileBytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BubbleDrawing.ServiceReference1.MxFileFormats FileFmt {
            get {
                return this.FileFmtField;
            }
            set {
                if ((this.FileFmtField.Equals(value) != true)) {
                    this.FileFmtField = value;
                    this.RaisePropertyChanged("FileFmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MxFileFormats", Namespace="http://schemas.datacontract.org/2004/07/HesCapeWS")]
    public enum MxFileFormats : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Access = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AltiumPCAD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutoCAD = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchTIF = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BITMAP = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cadds5 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CadStar = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAMWorks = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CDF = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorelDraw = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DesignSpace = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EdgeCAM = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eDrawing = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eSearch = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Esprit = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Excel = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FlowChart = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FrameMaker = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GIF = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GZero = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Helix = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IGES = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JPEG = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JPG = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MathCAD = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MATLAB = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatrixWorks = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ME10 = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Microstation = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Orcad = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outlook = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PADS = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAR = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParaCAD = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parasolid = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PcadMasterDesigner = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        POSTSCRIPT = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PowerPoint = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProE = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Project = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Relex = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Schema = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Solidworks = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SureTrak = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SWPrograms = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tango = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestExe = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TIF = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unigraphics = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Visio = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Word = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XML = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zip = 56,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEngrDrwTIFSvc")]
    public interface IEngrDrwTIFSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/RetCachedList", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/RetCachedListResponse")]
        BubbleDrawing.ServiceReference1.NameRevStruct[] RetCachedList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/RetCachedList", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/RetCachedListResponse")]
        System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.NameRevStruct[]> RetCachedListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/AddToCache", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/AddToCacheResponse")]
        BubbleDrawing.ServiceReference1.NameRevStruct AddToCache(string DrawingName, string DrawingRev, bool MakePDF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/AddToCache", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/AddToCacheResponse")]
        System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.NameRevStruct> AddToCacheAsync(string DrawingName, string DrawingRev, bool MakePDF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPkt", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPktResponse")]
        BubbleDrawing.ServiceReference1.EngrDrwPkt RetDrawingPkt(BubbleDrawing.ServiceReference1.NameRevStruct EngrDrwNameRev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPkt", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPktResponse")]
        System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.EngrDrwPkt> RetDrawingPktAsync(BubbleDrawing.ServiceReference1.NameRevStruct EngrDrwNameRev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPkt2", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPkt2Response")]
        BubbleDrawing.ServiceReference1.EngrDrwPkt RetDrawingPkt2(string DrawingName, string DrawingRev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPkt2", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPkt2Response")]
        System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.EngrDrwPkt> RetDrawingPkt2Async(string DrawingName, string DrawingRev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPktPDF", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPktPDFResponse")]
        BubbleDrawing.ServiceReference1.EngrDrwPkt RetDrawingPktPDF(BubbleDrawing.ServiceReference1.NameRevStruct EngrDrwNameRev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPktPDF", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPktPDFResponse")]
        System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.EngrDrwPkt> RetDrawingPktPDFAsync(BubbleDrawing.ServiceReference1.NameRevStruct EngrDrwNameRev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPktPDF2", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPktPDF2Response")]
        BubbleDrawing.ServiceReference1.EngrDrwPkt RetDrawingPktPDF2(string DrawingName, string DrawingRev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPktPDF2", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/RetDrawingPktPDF2Response")]
        System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.EngrDrwPkt> RetDrawingPktPDF2Async(string DrawingName, string DrawingRev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/DrwPDFPaths", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/DrwPDFPathsResponse")]
        string[] DrwPDFPaths(BubbleDrawing.ServiceReference1.NameRevStruct NameRev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEngrDrwTIFSvc/DrwPDFPaths", ReplyAction="http://tempuri.org/IEngrDrwTIFSvc/DrwPDFPathsResponse")]
        System.Threading.Tasks.Task<string[]> DrwPDFPathsAsync(BubbleDrawing.ServiceReference1.NameRevStruct NameRev);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEngrDrwTIFSvcChannel : BubbleDrawing.ServiceReference1.IEngrDrwTIFSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EngrDrwTIFSvcClient : System.ServiceModel.ClientBase<BubbleDrawing.ServiceReference1.IEngrDrwTIFSvc>, BubbleDrawing.ServiceReference1.IEngrDrwTIFSvc {
        
        public EngrDrwTIFSvcClient() {
        }
        
        public EngrDrwTIFSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EngrDrwTIFSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EngrDrwTIFSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EngrDrwTIFSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BubbleDrawing.ServiceReference1.NameRevStruct[] RetCachedList() {
            return base.Channel.RetCachedList();
        }
        
        public System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.NameRevStruct[]> RetCachedListAsync() {
            return base.Channel.RetCachedListAsync();
        }
        
        public BubbleDrawing.ServiceReference1.NameRevStruct AddToCache(string DrawingName, string DrawingRev, bool MakePDF) {
            return base.Channel.AddToCache(DrawingName, DrawingRev, MakePDF);
        }
        
        public System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.NameRevStruct> AddToCacheAsync(string DrawingName, string DrawingRev, bool MakePDF) {
            return base.Channel.AddToCacheAsync(DrawingName, DrawingRev, MakePDF);
        }
        
        public BubbleDrawing.ServiceReference1.EngrDrwPkt RetDrawingPkt(BubbleDrawing.ServiceReference1.NameRevStruct EngrDrwNameRev) {
            return base.Channel.RetDrawingPkt(EngrDrwNameRev);
        }
        
        public System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.EngrDrwPkt> RetDrawingPktAsync(BubbleDrawing.ServiceReference1.NameRevStruct EngrDrwNameRev) {
            return base.Channel.RetDrawingPktAsync(EngrDrwNameRev);
        }
        
        public BubbleDrawing.ServiceReference1.EngrDrwPkt RetDrawingPkt2(string DrawingName, string DrawingRev) {
            return base.Channel.RetDrawingPkt2(DrawingName, DrawingRev);
        }
        
        public System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.EngrDrwPkt> RetDrawingPkt2Async(string DrawingName, string DrawingRev) {
            return base.Channel.RetDrawingPkt2Async(DrawingName, DrawingRev);
        }
        
        public BubbleDrawing.ServiceReference1.EngrDrwPkt RetDrawingPktPDF(BubbleDrawing.ServiceReference1.NameRevStruct EngrDrwNameRev) {
            return base.Channel.RetDrawingPktPDF(EngrDrwNameRev);
        }
        
        public System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.EngrDrwPkt> RetDrawingPktPDFAsync(BubbleDrawing.ServiceReference1.NameRevStruct EngrDrwNameRev) {
            return base.Channel.RetDrawingPktPDFAsync(EngrDrwNameRev);
        }
        
        public BubbleDrawing.ServiceReference1.EngrDrwPkt RetDrawingPktPDF2(string DrawingName, string DrawingRev) {
            return base.Channel.RetDrawingPktPDF2(DrawingName, DrawingRev);
        }
        
        public System.Threading.Tasks.Task<BubbleDrawing.ServiceReference1.EngrDrwPkt> RetDrawingPktPDF2Async(string DrawingName, string DrawingRev) {
            return base.Channel.RetDrawingPktPDF2Async(DrawingName, DrawingRev);
        }
        
        public string[] DrwPDFPaths(BubbleDrawing.ServiceReference1.NameRevStruct NameRev) {
            return base.Channel.DrwPDFPaths(NameRev);
        }
        
        public System.Threading.Tasks.Task<string[]> DrwPDFPathsAsync(BubbleDrawing.ServiceReference1.NameRevStruct NameRev) {
            return base.Channel.DrwPDFPathsAsync(NameRev);
        }
    }
}
