
const  initialState = {
    win: {
        width: 1617,
        height: 785,
    },
    maxsize: 32767,
    maxScaleSize:12800,
    aspectRatio: 16 / 9,
    scrollPosition: 0,
    konvaPositionTop: 0,
    documentPositionTop: 0,
    moveScrollPosition: 0,
    selectedRowIndex:null,
    fitscreen: false,
    zoomed: false,
    prev:null,
    zoomingfactor: 0,
    pad: 20,
    width: 100,
    height: 100,
    drawingNo: "",
    revNo: "",
    loadingText : "",
    sidebarIsOpen: false,
    isLoading: false,
    isErrImage:false,
    topbarIsOpen: false,
    selectedRegion: "",
    bgImgRotation: 0,
    bgImgW: 100,
    bgImgH: 100,
    bgImgX: 100,
    bgImgY: 100,
    bgImgScale: 1,
    imgscale:1,
    InitialScale: 1,
    scaleStep:0,
    rotateX: 0,
    rotateY:0,
    ItemView: null,
    selectAnnotation: null,
    history: [],
    user: [],
    sessionId: "",
    draft: [],
    partial_image: [],
    immutableStore: [],
    drawingDetails: [],
    drawingHeader: [],
    drawingRegions: [],
    balloonRegions: [],
    originalRegions: [],
    zoomoriginalRegions: [],
    lmtype: [],
    lmsubtype: [],
    units: [],
    cmbTolerance:[],
    savedDetails:false,
    loadingTextSize: "30px",
    scrollHeight: window.scrollY,
    isDisabledSearchBtn:false,
    isDisabledACT: true,
    isDisabledFIT: true,
    isDisabledZoomOut: true,
    isDisabledZoomIn: true,
    isDisabledCCW: true,
    isDisabledCW: true,
    isDisabledMAG: true,
    isDisabledFH: true,
    isDisabledDel: true,
    isDisabledSave: true,
    isDisabledReset: false,
    isDisabledResetB: true,
    isDisabledAutoB: true,
    isDisabledOCR: true,
    isDisabledMove: true,
    isDisabledRegion: true,
    isDisabledSPL: true,
    isDisabledSelected: true,
    isDisabledManual: true,
    isDisabledUnSelected:true,
    intBubble: 0,
    isMultifile: false,
    selectedBalloon:null,
    is_BalloonDrawingSaved: false,
    AppSettings: []

};

export default initialState;